services:
  app:
    image: ruby:3.3.5
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3010', '-b', '0.0.0.0']
    ports:
      - '127.0.0.1:3010:3010'
    working_dir: /app
    environment:
      BUNDLE_PATH: /bundle
    volumes:
      - ./:/app
      - bundle:/bundle
volumes:
  bundle:
    driver: local
