services:
  caddy:
    image: caddy
    ports:
      - '127.0.0.1:3011:3011'
    volumes:
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - attic
  attic:
    # image: ruby:3.3.5
    build: .
    command: ['bundle', 'exec', 'rails', 'server', '-p', '3010', '-b', '0.0.0.0']
    ports:
      - '127.0.0.1:3010:3010'
    working_dir: /app
    environment:
      BUNDLE_PATH: /bundle
      # RUBY_DEBUG_OPEN: true
    env_file:
      - .env.development
    volumes:
      - ./:/app
      - bundle:/bundle
    tmpfs:
      - /app/tmp/pids
    depends_on:
      - mongo
    networks:
      - attic
      - default
  mongo:
    image: mongo

volumes:
  bundle:
    driver: local
  caddy_data:
    driver: local

networks:
  attic:
    name: attic
    driver: bridge
