services:
  app:
    image: node
    command: ['npm', 'run', 'dev']
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 127.0.0.1:5173:5173
volumes:
  node_modules:
    driver: local
